import type { CrfTemplateDef } from '../types'

export const DMA2026_TEMPLATE: CrfTemplateDef = {
  study_code: 'DMA2026',
  version: '1.0',
  visitSchedule: ['Day 0 (Basal)', 'Day 14 (1st Visit)', 'Day 28 (2nd Visit)', 'Day 42 (3rd Visit)', 'Day 56 (4th Visit)', 'Day 70 (5th Visit)', 'Day 84 (6th Visit / AT)'],
  sections: [
    // 1. ENROLLMENT
    {
      key: 'enrollment',
      title: '1. Enrollment Details',
      fields: [
        { key: 'trial_group', label: 'Trial Group', type: 'text', required: true },
        { key: 'centre', label: 'Centre', type: 'text', required: true },
        { key: 'cr_no', label: 'CR No.', type: 'text', required: true },
        { key: 'opd_no', label: 'OPD No.', type: 'text' },
        { key: 'gender', label: 'Gender', type: 'radio', options: [{ value: '1', label: 'Male' }, { value: '2', label: 'Female' }] },
        { key: 'age_years', label: 'Age (years)', type: 'number' },
        { key: 'age_months', label: 'Age (months)', type: 'number' },
        { key: 'dob', label: 'Date of Birth', type: 'date' },
        { key: 'address', label: 'Address', type: 'textarea' },
        { key: 'telephone', label: 'Telephone No.', type: 'text' },
      ],
    },

    // 2. INCLUSION CRITERIA
    {
      key: 'inclusion_criteria',
      title: '2. Inclusion Criteria',
      fields: [
        {
          key: 'ic_age',
          label: 'Patients of any gender aged 35–65 years diagnosed with Type 2 DM',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
        {
          key: 'ic_fbs',
          label: 'FBS ≥ 126 and ≤ 179 mg/dL',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
        {
          key: 'ic_hba1c',
          label: 'HbA1c ≥ 6.5% and ≤ 7.9%',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
        {
          key: 'ic_followup',
          label: 'Able to come for follow-up',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
        {
          key: 'ic_consent',
          label: 'Willing to participate and able to provide written informed consent',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
      ],
    },

    // 3. DEMOGRAPHIC PROFILE
    {
      key: 'demographic',
      title: '3. Demographic Profile',
      fields: [
        {
          key: 'marital_status',
          label: 'Marital Status',
          type: 'select',
          options: [
            { value: '1', label: 'Married' },
            { value: '2', label: 'Unmarried' },
            { value: '3', label: 'Widow(er)' },
            { value: '4', label: 'Divorcee' },
          ],
        },
        {
          key: 'education',
          label: 'Educational Status',
          type: 'select',
          options: [
            { value: '1', label: 'Illiterate' },
            { value: '2', label: 'Literate' },
          ],
        },
        { key: 'education_detail', label: 'If Literate — Qualification', type: 'text' },
        {
          key: 'occupation',
          label: 'Occupation',
          type: 'select',
          options: [
            { value: '1', label: 'Physical Labour' },
            { value: '2', label: 'Desk Job' },
          ],
        },
        {
          key: 'socio_economic',
          label: 'Socio-Economic Status',
          type: 'radio',
          options: [{ value: '1', label: 'Above Poverty Line' }, { value: '2', label: 'Below Poverty Line' }],
        },
        {
          key: 'habitat',
          label: 'Habitat',
          type: 'radio',
          options: [{ value: '1', label: 'Urban' }, { value: '2', label: 'Rural' }],
        },
      ],
    },

    // 4. CHIEF COMPLAINTS
    {
      key: 'chief_complaints',
      title: '4. Chief Complaints',
      fields: [
        { key: 'cc_heading', label: 'Chief Complaint (Yes=1 / No=0) + Duration (months)', type: 'heading' },
        { key: 'cc_polyuria', label: 'Polyuria / Excessive Urine', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_polyuria_dur', label: 'Polyuria — Duration (months)', type: 'number' },
        { key: 'cc_polyphagia', label: 'Polyphagia / Excessive Hunger', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_polyphagia_dur', label: 'Polyphagia — Duration (months)', type: 'number' },
        { key: 'cc_polydipsia', label: 'Polydipsia / Excessive Thirst', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_polydipsia_dur', label: 'Polydipsia — Duration (months)', type: 'number' },
        { key: 'cc_exhaustion', label: 'Exhaustion / Tiredness', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_exhaustion_dur', label: 'Exhaustion — Duration (months)', type: 'number' },
        { key: 'cc_body_ache', label: 'Body Ache', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_body_ache_dur', label: 'Body Ache — Duration (months)', type: 'number' },
        { key: 'cc_giddiness', label: 'Giddiness', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_giddiness_dur', label: 'Giddiness — Duration (months)', type: 'number' },
        { key: 'cc_polyneuritis', label: 'Polyneuritis (Numbness / Tingling)', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_polyneuritis_dur', label: 'Polyneuritis — Duration (months)', type: 'number' },
        { key: 'cc_visual', label: 'Visual Disturbance', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'cc_visual_dur', label: 'Visual Disturbance — Duration (months)', type: 'number' },
        { key: 'cc_other', label: 'Any Other Complaint', type: 'text' },
        { key: 'cc_other_dur', label: 'Other — Duration (months)', type: 'number' },
      ],
    },

    // 5. HISTORY
    {
      key: 'history',
      title: '5. History',
      fields: [
        { key: 'hpi_heading', label: 'History of Present Illness', type: 'heading' },
        { key: 'hpi_duration', label: 'Duration of Illness', type: 'text' },
        { key: 'hpi_other', label: 'Any Other Information', type: 'textarea' },
        { key: 'prev_heading', label: 'History of Previous Illness', type: 'heading' },
        {
          key: 'prev_illness',
          label: 'Any Significant Medical / Surgical History',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
        },
        { key: 'prev_illness_detail', label: 'If Yes — Specify', type: 'textarea' },
      ],
    },

    // 6. PERSONAL HISTORY
    {
      key: 'personal_history',
      title: '6. Personal History',
      fields: [
        {
          key: 'diet',
          label: 'Dietary Habits',
          type: 'radio',
          options: [{ value: '1', label: 'Vegetarian' }, { value: '2', label: 'Non-Vegetarian' }],
        },
        {
          key: 'addictions',
          label: 'Addictions',
          type: 'select',
          options: [
            { value: '1', label: 'Smoking' },
            { value: '2', label: 'Tobacco' },
            { value: '3', label: 'Alcohol' },
            { value: '4', label: 'Substance Abuse' },
            { value: '5', label: 'None' },
          ],
        },
        {
          key: 'smoking_freq',
          label: 'Smoking Frequency',
          type: 'radio',
          options: [
            { value: '1', label: 'Regular' },
            { value: '2', label: 'Occasional' },
            { value: '3', label: 'Ex-smoker (stopped >1 yr)' },
            { value: '4', label: 'Never Smoked' },
          ],
        },
        { key: 'smoking_qty', label: 'Smoking Quantity (/day)', type: 'text' },
        { key: 'smoking_dur', label: 'Duration of Smoking', type: 'text' },
        {
          key: 'alcohol',
          label: 'Alcohol Intake',
          type: 'radio',
          options: [{ value: '0', label: 'No' }, { value: '1', label: 'Habitual' }, { value: '2', label: 'Occasional' }],
        },
        { key: 'alcohol_qty', label: 'Alcohol Quantity (/day)', type: 'text' },
        { key: 'alcohol_dur', label: 'Duration of Alcohol Intake', type: 'text' },
        {
          key: 'sleep',
          label: 'Sleep',
          type: 'radio',
          options: [{ value: '1', label: 'Normal' }, { value: '2', label: 'Disturbed' }],
        },
        {
          key: 'bowel',
          label: 'Bowel Habits',
          type: 'radio',
          options: [{ value: '1', label: 'Regular' }, { value: '2', label: 'Irregular' }],
        },
        {
          key: 'stool_consistency',
          label: 'Stool Consistency',
          type: 'radio',
          options: [{ value: '1', label: 'Normal' }, { value: '2', label: 'Loose' }, { value: '3', label: 'Constipated' }],
        },
        {
          key: 'urine_output',
          label: 'Urine Output',
          type: 'select',
          options: [
            { value: '1', label: 'Normal' },
            { value: '2', label: 'Frequent' },
            { value: '3', label: 'Urgency' },
            { value: '4', label: 'Strangury' },
            { value: '5', label: 'Nocturia' },
          ],
        },
        {
          key: 'exercise',
          label: 'Physical Exercise',
          type: 'select',
          options: [
            { value: '1', label: 'Heavy Labour' },
            { value: '2', label: 'Moderate Labour' },
            { value: '3', label: 'Office Job' },
            { value: '4', label: 'Sedentary' },
          ],
        },
        {
          key: 'emotional_stress',
          label: 'Emotional Stress',
          type: 'radio',
          options: [{ value: '1', label: 'Average' }, { value: '2', label: 'Moderate' }, { value: '3', label: 'Too Much' }],
        },
        { key: 'fh_heading', label: 'Family History', type: 'heading' },
        { key: 'fh_dm_mother', label: 'DM — Mother', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_dm_father', label: 'DM — Father', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_dm_sibling', label: 'DM — Sibling', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_htn_mother', label: 'HTN — Mother', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_htn_father', label: 'HTN — Father', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_htn_sibling', label: 'HTN — Sibling', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_cad_mother', label: 'CAD — Mother', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_cad_father', label: 'CAD — Father', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'fh_cad_sibling', label: 'CAD — Sibling', type: 'radio', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
        { key: 'gynae_heading', label: 'Gynaecological & Obstetric History (Female only)', type: 'heading' },
        { key: 'gynae_detail', label: 'Details', type: 'textarea' },
        { key: 'lmp', label: 'LMP', type: 'date' },
        { key: 'live_children', label: 'No. of Live Children', type: 'number' },
        { key: 'surgical_history', label: 'Surgical History', type: 'textarea' },
      ],
    },

    // 7. GENERAL PHYSICAL EXAMINATION
    {
      key: 'gpe',
      title: '7. General Physical Examination',
      fields: [
        {
          key: 'built',
          label: 'Built',
          type: 'radio',
          options: [{ value: '1', label: 'Average' }, { value: '2', label: 'Emaciated' }, { value: '3', label: 'Well Built' }],
        },
        {
          key: 'nutrition',
          label: 'Nutrition',
          type: 'radio',
          options: [{ value: '1', label: 'Moderately Nourished' }, { value: '2', label: 'Malnourished' }, { value: '3', label: 'Well Nourished' }],
        },
        { key: 'height', label: 'Height (m)', type: 'number' },
        { key: 'weight', label: 'Weight (kg)', type: 'number' },
        { key: 'bmi', label: 'BMI (Kg/m²)', type: 'number' },
        { key: 'waist_circumference', label: 'Waist Circumference (cm)', type: 'number' },
        { key: 'rr', label: 'Respiratory Rate (/min)', type: 'number' },
        { key: 'pr', label: 'Pulse Rate (/min)', type: 'number' },
        { key: 'bp', label: 'Blood Pressure (mmHg)', type: 'text' },
        {
          key: 'clubbing',
          label: 'Clubbing',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'cyanosis',
          label: 'Cyanosis',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Central' }, { value: '2', label: 'Peripheral' }],
        },
        { key: 'temperature', label: 'Temperature (°F)', type: 'number' },
        {
          key: 'pallor',
          label: 'Pallor',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'lymphadenopathy',
          label: 'Lymphadenopathy',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        { key: 'lymph_site', label: 'Lymphadenopathy — Site', type: 'text' },
        {
          key: 'edema',
          label: 'Oedema',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'edema_character',
          label: 'Oedema Character',
          type: 'radio',
          options: [{ value: '1', label: 'Pitting' }, { value: '2', label: 'Non-Pitting' }],
        },
        { key: 'edema_site', label: 'Oedema Site', type: 'text' },
        { key: 'hair', label: 'Hair', type: 'text' },
        { key: 'nails', label: 'Nails', type: 'text' },
        {
          key: 'vertebral_column',
          label: 'Vertebral Column',
          type: 'radio',
          options: [{ value: '1', label: 'Normal' }, { value: '2', label: 'Abnormal' }],
        },
        {
          key: 'joints',
          label: 'Joints',
          type: 'radio',
          options: [{ value: '1', label: 'Normal' }, { value: '2', label: 'Abnormal' }],
        },
        { key: 'joints_detail', label: 'Joints — Specific abnormality', type: 'textarea' },
      ],
    },

    // 8. SYSTEMIC EXAMINATION
    {
      key: 'systemic_exam',
      title: '8. Systemic Examination',
      fields: [
        { key: 'resp', label: 'Respiratory System', type: 'textarea' },
        { key: 'gi', label: 'Gastro-Intestinal System', type: 'textarea' },
        { key: 'cvs', label: 'Cardio-Vascular System', type: 'textarea' },
        { key: 'ns', label: 'Nervous System', type: 'textarea' },
        { key: 'msk', label: 'Musculo-Skeletal System', type: 'textarea' },
        { key: 'gu', label: 'Genito-Urinary System', type: 'textarea' },
      ],
    },

    // 9. AYURVEDIC PARAMETERS
    {
      key: 'ayurvedic_params',
      title: '9. Ayurvedic Parameters',
      fields: [
        { key: 'ah_heading', label: 'Aahar (Diet)', type: 'heading' },
        {
          key: 'appetite',
          label: 'Appetite',
          type: 'radio',
          options: [{ value: 'good', label: 'Good' }, { value: 'moderate', label: 'Moderate' }, { value: 'poor', label: 'Poor' }],
        },
        {
          key: 'rasa_pradhanata',
          label: 'Dominance of Rasa in Diet',
          type: 'select',
          options: [
            { value: 'M', label: 'Madhura (Sweet)' },
            { value: 'A', label: 'Amla (Sour)' },
            { value: 'L', label: 'Lavana (Salt)' },
            { value: 'Kt', label: 'Katu (Pungent)' },
            { value: 'T', label: 'Tikta (Bitter)' },
            { value: 'Ks', label: 'Kashaya (Astringent)' },
          ],
        },
        {
          key: 'dietary_habits',
          label: 'Dietary Habits Type',
          type: 'select',
          options: [
            { value: 'samasana', label: 'Samasana' },
            { value: 'adhyasana', label: 'Adhyasana' },
            { value: 'vishamasana', label: 'Vishamasana' },
            { value: 'pramitasana', label: 'Pramitasana' },
            { value: 'virudhahara', label: 'Virudhahara' },
          ],
        },
        { key: 'vi_heading', label: 'Viharaja (Daily Routine)', type: 'heading' },
        {
          key: 'vyayama',
          label: 'Vyayama (Exercise)',
          type: 'select',
          options: [
            { value: 'regularly', label: 'Regularly' },
            { value: 'irregularly', label: 'Irregularly' },
            { value: 'no', label: 'No' },
            { value: 'less', label: 'Less' },
            { value: 'proper', label: 'Proper' },
            { value: 'excess', label: 'Excess' },
          ],
        },
        { key: 'vishrama_day', label: 'Vishrama — Day (hrs)', type: 'number' },
        { key: 'vishrama_night', label: 'Vishrama — Night (hrs)', type: 'number' },
        {
          key: 'snana',
          label: 'Snana (Bathing)',
          type: 'radio',
          options: [{ value: 'daily', label: 'Daily' }, { value: 'irregular', label: 'Irregular' }],
        },
        {
          key: 'abhyanga',
          label: 'Abhyanga (Oil Massage)',
          type: 'radio',
          options: [{ value: 'daily', label: 'Daily' }, { value: 'occasionally', label: 'Occasionally' }, { value: 'nil', label: 'Nil' }],
        },
        { key: 'ko_heading', label: 'Koshtha', type: 'heading' },
        {
          key: 'koshtha',
          label: 'Koshtha',
          type: 'radio',
          options: [{ value: 'mridu', label: 'Mridu' }, { value: 'madhya', label: 'Madhya' }, { value: 'krura', label: 'Krura' }],
        },
        { key: 'mala_times', label: 'Mala Pravritti (times/day)', type: 'number' },
        { key: 'mo_heading', label: 'Mootra Pravritti (Urination)', type: 'heading' },
        {
          key: 'mootra',
          label: 'Mootra Pravritti',
          type: 'select',
          options: [
            { value: 'samyak', label: 'Samyak' },
            { value: 'krucchra', label: 'Krucchra' },
            { value: 'vaivarnya', label: 'Vaivarnya' },
            { value: 'daaha', label: 'Daaha' },
            { value: 'alpa', label: 'Alpa' },
            { value: 'prabhuta', label: 'Prabhuta' },
            { value: 'avila', label: 'Avila' },
          ],
        },
        { key: 'mootra_freq_day', label: 'Mootra Frequency — Day (/day)', type: 'number' },
        { key: 'mootra_freq_night', label: 'Mootra Frequency — Night (/night)', type: 'number' },
      ],
    },

    // 10. PRAKRITI & DASHAKRITA ASSESSMENT
    {
      key: 'prakriti_assessment',
      title: '10. Prakriti & Dashakrita Assessment',
      fields: [
        {
          key: 'prakriti',
          label: 'Prakriti',
          type: 'select',
          options: [
            { value: '1', label: 'Vataja' },
            { value: '2', label: 'Pittaja' },
            { value: '3', label: 'Kaphaja' },
            { value: '4', label: 'Vata-Pittaja' },
            { value: '5', label: 'Vata-Kaphaja' },
            { value: '6', label: 'Pitta-Kaphaja' },
            { value: '7', label: 'Sannipataja' },
          ],
        },
        {
          key: 'saara',
          label: 'Saara',
          type: 'select',
          options: [
            { value: '1', label: 'Twak Saara' },
            { value: '2', label: 'Rakta Saara' },
            { value: '3', label: 'Mamsa Saara' },
            { value: '4', label: 'Meda Saara' },
            { value: '5', label: 'Asthi Saara' },
            { value: '6', label: 'Majja Saara' },
            { value: '7', label: 'Shukra Saara' },
          ],
        },
        {
          key: 'samhanana',
          label: 'Samhanana',
          type: 'radio',
          options: [{ value: '1', label: 'Pravara' }, { value: '2', label: 'Madhyama' }, { value: '3', label: 'Avara' }],
        },
        {
          key: 'satmya',
          label: 'Satmya',
          type: 'radio',
          options: [{ value: '1', label: 'Pravara Satmya' }, { value: '2', label: 'Madhyama Satmya' }, { value: '3', label: 'Avara Satmya' }],
        },
        {
          key: 'satva',
          label: 'Satva',
          type: 'radio',
          options: [{ value: '1', label: 'Pravara Satva' }, { value: '2', label: 'Madhyama Satva' }, { value: '3', label: 'Avara Satva' }],
        },
        {
          key: 'ahara_shakti',
          label: 'Ahara Shakti',
          type: 'radio',
          options: [{ value: '1', label: 'Pravara' }, { value: '2', label: 'Madhyama' }, { value: '3', label: 'Avara' }],
        },
        {
          key: 'vyayama_shakti',
          label: 'Vyayama Shakti',
          type: 'radio',
          options: [{ value: '1', label: 'Pravara' }, { value: '2', label: 'Madhyama' }, { value: '3', label: 'Avara' }],
        },
      ],
    },

    // 11. INVESTIGATIONS
    {
      key: 'investigations',
      title: '11. Laboratory Investigations',
      fields: [
        { key: 'hae_heading', label: 'Haematology', type: 'heading' },
        { key: 'hb_bt', label: 'Haemoglobin BT (g/dL)', type: 'number' },
        { key: 'hb_at', label: 'Haemoglobin AT (g/dL)', type: 'number' },
        { key: 'tlc_bt', label: 'TLC BT', type: 'number' },
        { key: 'tlc_at', label: 'TLC AT', type: 'number' },
        { key: 'dlc_n_bt', label: 'DLC N% BT', type: 'number' },
        { key: 'dlc_e_bt', label: 'DLC E% BT', type: 'number' },
        { key: 'dlc_b_bt', label: 'DLC B% BT', type: 'number' },
        { key: 'dlc_l_bt', label: 'DLC L% BT', type: 'number' },
        { key: 'dlc_m_bt', label: 'DLC M% BT', type: 'number' },
        { key: 'dlc_n_at', label: 'DLC N% AT', type: 'number' },
        { key: 'dlc_e_at', label: 'DLC E% AT', type: 'number' },
        { key: 'dlc_b_at', label: 'DLC B% AT', type: 'number' },
        { key: 'dlc_l_at', label: 'DLC L% AT', type: 'number' },
        { key: 'dlc_m_at', label: 'DLC M% AT', type: 'number' },
        { key: 'esr_bt', label: 'ESR BT (mm)', type: 'number' },
        { key: 'esr_at', label: 'ESR AT (mm)', type: 'number' },
        { key: 'bs_heading', label: 'Blood Sugar', type: 'heading' },
        { key: 'fbs_bt', label: 'FBS BT (mg/dL)', type: 'number' },
        { key: 'fbs_at', label: 'FBS AT (mg/dL)', type: 'number' },
        { key: 'ppbs_bt', label: 'PPBS BT (mg/dL)', type: 'number' },
        { key: 'ppbs_at', label: 'PPBS AT (mg/dL)', type: 'number' },
        { key: 'hba1c_bt', label: 'HbA1c BT (%)', type: 'number' },
        { key: 'hba1c_at', label: 'HbA1c AT (%)', type: 'number' },
        { key: 'lft_heading', label: 'LFT (Liver Function Tests)', type: 'heading' },
        { key: 'tbil_bt', label: 'Total Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'tbil_at', label: 'Total Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'dbil_bt', label: 'Direct Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'dbil_at', label: 'Direct Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'ibil_bt', label: 'Indirect Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'ibil_at', label: 'Indirect Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'alp_bt', label: 'S. Alkaline Phosphatase BT (U/L)', type: 'number' },
        { key: 'alp_at', label: 'S. Alkaline Phosphatase AT (U/L)', type: 'number' },
        { key: 'sgot_bt', label: 'SGOT / AST BT (karmen units/dL)', type: 'number' },
        { key: 'sgot_at', label: 'SGOT / AST AT (karmen units/dL)', type: 'number' },
        { key: 'sgpt_bt', label: 'SGPT / ALT BT (karmen units/dL)', type: 'number' },
        { key: 'sgpt_at', label: 'SGPT / ALT AT (karmen units/dL)', type: 'number' },
        { key: 'tp_bt', label: 'Total Protein BT (g/dL)', type: 'number' },
        { key: 'tp_at', label: 'Total Protein AT (g/dL)', type: 'number' },
        { key: 'albumin_bt', label: 'S. Albumin BT (g/dL)', type: 'number' },
        { key: 'albumin_at', label: 'S. Albumin AT (g/dL)', type: 'number' },
        { key: 'globulin_bt', label: 'S. Globulin BT (g/dL)', type: 'number' },
        { key: 'globulin_at', label: 'S. Globulin AT (g/dL)', type: 'number' },
        { key: 'ag_ratio_bt', label: 'A/G Ratio BT', type: 'number' },
        { key: 'ag_ratio_at', label: 'A/G Ratio AT', type: 'number' },
        { key: 'kft_heading', label: 'KFT (Kidney Function Tests)', type: 'heading' },
        { key: 'urea_bt', label: 'Serum Urea BT (mg/dL)', type: 'number' },
        { key: 'urea_at', label: 'Serum Urea AT (mg/dL)', type: 'number' },
        { key: 'creatinine_bt', label: 'Serum Creatinine BT (mg/dL)', type: 'number' },
        { key: 'creatinine_at', label: 'Serum Creatinine AT (mg/dL)', type: 'number' },
        { key: 'uric_acid_bt', label: 'Uric Acid BT (mg/dL)', type: 'number' },
        { key: 'uric_acid_at', label: 'Uric Acid AT (mg/dL)', type: 'number' },
        { key: 'lipid_heading', label: 'Serum Lipid Profile', type: 'heading' },
        { key: 'chol_bt', label: 'S. Cholesterol BT (mg/dL)', type: 'number' },
        { key: 'chol_at', label: 'S. Cholesterol AT (mg/dL)', type: 'number' },
        { key: 'hdl_bt', label: 'HDLc BT (mg/dL)', type: 'number' },
        { key: 'hdl_at', label: 'HDLc AT (mg/dL)', type: 'number' },
        { key: 'ldl_bt', label: 'LDLc BT (mg/dL)', type: 'number' },
        { key: 'ldl_at', label: 'LDLc AT (mg/dL)', type: 'number' },
        { key: 'vldl_bt', label: 'VLDL BT (mg/dL)', type: 'number' },
        { key: 'vldl_at', label: 'VLDL AT (mg/dL)', type: 'number' },
        { key: 'tg_bt', label: 'Serum Triglycerides BT (mg/dL)', type: 'number' },
        { key: 'tg_at', label: 'Serum Triglycerides AT (mg/dL)', type: 'number' },
        { key: 'chol_hdl_bt', label: 'Cholesterol/HDLc Ratio BT', type: 'number' },
        { key: 'chol_hdl_at', label: 'Cholesterol/HDLc Ratio AT', type: 'number' },
        { key: 'ldl_hdl_bt', label: 'LDL/HDL Ratio BT', type: 'number' },
        { key: 'ldl_hdl_at', label: 'LDL/HDL Ratio AT', type: 'number' },
        { key: 'urine_heading', label: 'Urine Examination', type: 'heading' },
        {
          key: 'urine_sugar_bt',
          label: 'Urine Sugar BT',
          type: 'select',
          options: [{ value: '0', label: 'Nil (0)' }, { value: '1', label: '+ (1)' }, { value: '2', label: '++ (2)' }, { value: '3', label: '+++ (3)' }],
        },
        {
          key: 'urine_sugar_at',
          label: 'Urine Sugar AT',
          type: 'select',
          options: [{ value: '0', label: 'Nil (0)' }, { value: '1', label: '+ (1)' }, { value: '2', label: '++ (2)' }, { value: '3', label: '+++ (3)' }],
        },
        {
          key: 'urine_protein_bt',
          label: 'Urine Protein BT',
          type: 'select',
          options: [{ value: '0', label: 'Nil (0)' }, { value: '1', label: '+ (1)' }, { value: '2', label: '++ (2)' }, { value: '3', label: '+++ (3)' }],
        },
        {
          key: 'urine_protein_at',
          label: 'Urine Protein AT',
          type: 'select',
          options: [{ value: '0', label: 'Nil (0)' }, { value: '1', label: '+ (1)' }, { value: '2', label: '++ (2)' }, { value: '3', label: '+++ (3)' }],
        },
        { key: 'urine_wbc_bt', label: 'Urine WBC BT (cells/hpf)', type: 'number' },
        { key: 'urine_wbc_at', label: 'Urine WBC AT (cells/hpf)', type: 'number' },
        { key: 'urine_rbc_bt', label: 'Urine RBC BT (cells/hpf)', type: 'number' },
        { key: 'urine_rbc_at', label: 'Urine RBC AT (cells/hpf)', type: 'number' },
      ],
    },

    // 12. FOLLOW-UP ASSESSMENT GRID (12 symptoms × 7 visits)
    {
      key: 'followup_assessment',
      title: '12. Follow-Up Assessment (Symptom Grading)',
      fields: [
        {
          key: 'followup_grid',
          label: 'Symptom Grades — Basal / 1st / 2nd / 3rd / 4th / 5th / 6th Visit',
          type: 'assessment_grid',
          rows: [
            'Prabhoota mootrata (Excessive Urine)',
            'Avila mootrata (Turbid Urine)',
            'Kshudhaadhikya — Polyphagia (Excessive Hunger)',
            'Pipasaadhikya — Polydipsia (Excessive Thirst)',
            'Mutramadhurya (Glycosuria)',
            'Suptaangta/Daha — Polyneuritis (Numbness/Burning of Soles)',
            'Pindikodveshtana (Cramps / Calf Muscle Pain)',
            'Vibandh (Constipation)',
            'Swedadikya (Excess Perspiration)',
            'Anga gandha (Bad Odour)',
            'Nidraadhikya (Excessive Sleep)',
            'Hasta Paad Tal Daha',
          ],
          columns: ['Basal', '1st Visit', '2nd Visit', '3rd Visit', '4th Visit', '5th Visit', '6th Visit'],
        },
        { key: 'followup_total_bt', label: 'Total Score BT', type: 'number' },
        { key: 'followup_total_at', label: 'Total Score AT (6th visit)', type: 'number' },
        { key: 'result', label: 'Result', type: 'text' },
        {
          key: 'improved',
          label: 'Improved / Not Improved',
          type: 'radio',
          options: [{ value: '1', label: 'Improved' }, { value: '0', label: 'Not Improved' }],
        },
        { key: 'adverse_effects', label: 'Adverse Effects (if any)', type: 'textarea' },
        { key: 'drug_provided', label: 'Drug Provided for (days)', type: 'text' },
        { key: 'next_visit_date', label: 'Date for Next Assessment', type: 'date' },
      ],
    },

    // 13. SF-12 HEALTH SURVEY
    {
      key: 'sf12',
      title: '13. SF-12 Health Survey',
      fields: [
        {
          key: 'sf12_q1_bt',
          label: 'Q1. In general, would you say your health is? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Excellent' },
            { value: '2', label: 'Very Good' },
            { value: '3', label: 'Good' },
            { value: '4', label: 'Fair' },
            { value: '5', label: 'Poor' },
          ],
        },
        {
          key: 'sf12_q1_at',
          label: 'Q1. In general, would you say your health is? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Excellent' },
            { value: '2', label: 'Very Good' },
            { value: '3', label: 'Good' },
            { value: '4', label: 'Fair' },
            { value: '5', label: 'Poor' },
          ],
        },
        {
          key: 'sf12_q2_bt',
          label: 'Q2. Moderate activities (moving table, vacuum, bowling, golf) — Health limits? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Yes, Limited a Lot' },
            { value: '2', label: 'Yes, Limited a Little' },
            { value: '3', label: 'No, Not Limited at All' },
          ],
        },
        {
          key: 'sf12_q2_at',
          label: 'Q2. Moderate activities — Health limits? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Yes, Limited a Lot' },
            { value: '2', label: 'Yes, Limited a Little' },
            { value: '3', label: 'No, Not Limited at All' },
          ],
        },
        {
          key: 'sf12_q3_bt',
          label: 'Q3. Climbing several flights of stairs — Health limits? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Yes, Limited a Lot' },
            { value: '2', label: 'Yes, Limited a Little' },
            { value: '3', label: 'No, Not Limited at All' },
          ],
        },
        {
          key: 'sf12_q3_at',
          label: 'Q3. Climbing several flights of stairs — Health limits? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Yes, Limited a Lot' },
            { value: '2', label: 'Yes, Limited a Little' },
            { value: '3', label: 'No, Not Limited at All' },
          ],
        },
        {
          key: 'sf12_q4_bt',
          label: 'Q4. Accomplished less than you would like (physical health)? (BT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q4_at',
          label: 'Q4. Accomplished less than you would like (physical health)? (AT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q5_bt',
          label: 'Q5. Limited in kind of work/activities (physical health)? (BT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q5_at',
          label: 'Q5. Limited in kind of work/activities (physical health)? (AT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q6_bt',
          label: 'Q6. Accomplished less than you would like (emotional problems)? (BT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q6_at',
          label: 'Q6. Accomplished less than you would like (emotional problems)? (AT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q7_bt',
          label: 'Q7. Did work less carefully than usual (emotional problems)? (BT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q7_at',
          label: 'Q7. Did work less carefully than usual (emotional problems)? (AT)',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'sf12_q8_bt',
          label: 'Q8. Pain interfered with normal work? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Not at All' },
            { value: '2', label: 'A Little Bit' },
            { value: '3', label: 'Moderately' },
            { value: '4', label: 'Quite a Bit' },
            { value: '5', label: 'Extremely' },
          ],
        },
        {
          key: 'sf12_q8_at',
          label: 'Q8. Pain interfered with normal work? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'Not at All' },
            { value: '2', label: 'A Little Bit' },
            { value: '3', label: 'Moderately' },
            { value: '4', label: 'Quite a Bit' },
            { value: '5', label: 'Extremely' },
          ],
        },
        {
          key: 'sf12_q9_bt',
          label: 'Q9. Have you felt calm & peaceful (past 4 weeks)? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q9_at',
          label: 'Q9. Have you felt calm & peaceful (past 4 weeks)? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q10_bt',
          label: 'Q10. Did you have a lot of energy (past 4 weeks)? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q10_at',
          label: 'Q10. Did you have a lot of energy (past 4 weeks)? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q11_bt',
          label: 'Q11. Have you felt down-hearted and blue (past 4 weeks)? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q11_at',
          label: 'Q11. Have you felt down-hearted and blue (past 4 weeks)? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'A Good Bit of the Time' },
            { value: '4', label: 'Some of the Time' },
            { value: '5', label: 'A Little of the Time' },
            { value: '6', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q12_bt',
          label: 'Q12. Physical/emotional problems interfered with social activities? (BT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All of the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'Some of the Time' },
            { value: '4', label: 'A Little of the Time' },
            { value: '5', label: 'None of the Time' },
          ],
        },
        {
          key: 'sf12_q12_at',
          label: 'Q12. Physical/emotional problems interfered with social activities? (AT)',
          type: 'radio',
          options: [
            { value: '1', label: 'All of the Time' },
            { value: '2', label: 'Most of the Time' },
            { value: '3', label: 'Some of the Time' },
            { value: '4', label: 'A Little of the Time' },
            { value: '5', label: 'None of the Time' },
          ],
        },
        { key: 'pcs_bt', label: 'PCS Score BT', type: 'number' },
        { key: 'pcs_at', label: 'PCS Score AT', type: 'number' },
        { key: 'mcs_bt', label: 'MCS Score BT', type: 'number' },
        { key: 'mcs_at', label: 'MCS Score AT', type: 'number' },
      ],
    },
  ],
}
