import type { CrfTemplateDef } from '../types'

const CLDQ_OPTIONS = [
  { value: '7', label: 'All of the time' },
  { value: '6', label: 'Most of the time' },
  { value: '5', label: 'A good bit of the time' },
  { value: '4', label: 'Some of the time' },
  { value: '3', label: 'A little of the time' },
  { value: '2', label: 'Hardly any of the time' },
  { value: '1', label: 'None of the time' },
]

export const FLD2026_TEMPLATE: CrfTemplateDef = {
  study_code: 'FLD2026',
  version: '1.0',
  sections: [
    // 1. ENROLLMENT
    {
      key: 'enrollment',
      title: '1. Enrollment Details',
      fields: [
        {
          key: 'research_group',
          label: 'Research Group',
          type: 'radio',
          options: [{ value: 'A', label: 'Group A' }, { value: 'B', label: 'Group B' }],
          required: true,
        },
        { key: 'research_case_no', label: 'Research Case No.', type: 'text', required: true },
        { key: 'opd_ipd_no', label: 'OPD / IPD No.', type: 'text' },
        { key: 'cr_no', label: 'C.R. No.', type: 'text' },
        { key: 'date_admission', label: 'Date of Admission', type: 'date' },
        { key: 'date_discharge', label: 'Date of Discharge', type: 'date' },
        { key: 'date_commencement', label: 'Date of Commencement', type: 'date' },
        { key: 'date_completion', label: 'Date of Completion', type: 'date' },
        { key: 'duration_trial', label: 'Duration of Trial', type: 'text' },
        {
          key: 'result',
          label: 'Result',
          type: 'radio',
          options: [
            { value: 'cured', label: 'Cured' },
            { value: 'improved', label: 'Improved' },
            { value: 'discontinued', label: 'Discontinued' },
          ],
        },
        { key: 'religion', label: 'Religion', type: 'text' },
        {
          key: 'occupation_type',
          label: 'Occupation',
          type: 'select',
          options: [
            { value: 'service', label: 'Service' },
            { value: 'business', label: 'Business' },
            { value: 'housewife', label: 'Housewife' },
            { value: 'student', label: 'Student' },
          ],
        },
        {
          key: 'socioeconomic',
          label: 'Socioeconomic Status',
          type: 'select',
          options: [
            { value: 'poor', label: 'Poor' },
            { value: 'middle', label: 'Middle' },
            { value: 'upper_middle', label: 'Upper Middle' },
            { value: 'upper', label: 'Upper' },
          ],
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          type: 'select',
          options: [
            { value: 'married', label: 'Married' },
            { value: 'unmarried', label: 'Unmarried' },
            { value: 'widow', label: 'Widow/Widower' },
            { value: 'divorced', label: 'Divorced' },
          ],
        },
        { key: 'address', label: 'Address', type: 'textarea' },
      ],
    },

    // 2. COMPLAINTS & HISTORY
    {
      key: 'complaints_history',
      title: '2. Complaints & History',
      fields: [
        { key: 'chief_complaints', label: 'Chief Complaints with Duration', type: 'textarea', required: true },
        { key: 'associated_complaints', label: 'Associated Complaints with Duration', type: 'textarea' },
        { key: 'hpi', label: 'History of Present Illness', type: 'textarea' },
        { key: 'past_illness', label: 'History of Past Illness', type: 'textarea' },
        { key: 'family_history', label: 'Family History', type: 'textarea' },
        { key: 'treatment_medical', label: 'Treatment History — Medical', type: 'textarea' },
        { key: 'treatment_surgical', label: 'Treatment History — Surgical', type: 'textarea' },
      ],
    },

    // 3. PERSONAL HISTORY
    {
      key: 'personal_history',
      title: '3. Personal History',
      fields: [
        {
          key: 'diet',
          label: 'Diet',
          type: 'radio',
          options: [{ value: 'veg', label: 'Vegetarian' }, { value: 'mixed', label: 'Mixed' }],
        },
        {
          key: 'dominant_rasa',
          label: 'Dominant Rasa in Diet',
          type: 'select',
          options: [
            { value: 'M', label: 'Madhura (Sweet)' },
            { value: 'A', label: 'Amla (Sour)' },
            { value: 'L', label: 'Lavana (Salt)' },
            { value: 'K', label: 'Katu (Pungent)' },
            { value: 'T', label: 'Tikta (Bitter)' },
            { value: 'Ks', label: 'Kashaya (Astringent)' },
          ],
        },
        {
          key: 'nature_diet',
          label: 'Nature of Diet',
          type: 'select',
          options: [
            { value: 'carb_rich', label: 'Carbohydrate Rich' },
            { value: 'fat_rich', label: 'Fat Rich' },
            { value: 'protein_rich', label: 'Protein Rich' },
          ],
        },
        {
          key: 'dietary_habits',
          label: 'Dietary Habits',
          type: 'select',
          options: [
            { value: 'samasana', label: 'Samasana' },
            { value: 'adhyasana', label: 'Adhyasana' },
            { value: 'vishmasana', label: 'Vishmasana' },
          ],
        },
        {
          key: 'diet_quantity',
          label: 'Quantity of Diet',
          type: 'radio',
          options: [{ value: 'alpa', label: 'Alpa' }, { value: 'madhyam', label: 'Madhyam' }, { value: 'adhika', label: 'Adhika' }],
        },
        {
          key: 'diet_qualities',
          label: 'Qualities of Diet',
          type: 'select',
          options: [
            { value: 'guru', label: 'Guru' },
            { value: 'sheet', label: 'Sheet' },
            { value: 'sleshmala', label: 'Sleshmala' },
            { value: 'madhur', label: 'Madhur' },
            { value: 'snigdha', label: 'Snigdha' },
            { value: 'abhishyandi', label: 'Abhishyandi' },
          ],
        },
        {
          key: 'birth_place',
          label: 'Birth Place / Desha',
          type: 'radio',
          options: [{ value: 'aanoop', label: 'Aanoop' }, { value: 'jangala', label: 'Jangala' }, { value: 'sadharana', label: 'Sadharana' }],
        },
        { key: 'occupation_detail', label: 'Occupational History (Nature / Working hrs / Resting hrs)', type: 'textarea' },
        {
          key: 'agni',
          label: 'Agni',
          type: 'radio',
          options: [
            { value: 'sama', label: 'Sama' },
            { value: 'vishama', label: 'Vishama' },
            { value: 'tikshna', label: 'Tikshna' },
            { value: 'manda', label: 'Manda' },
          ],
        },
        {
          key: 'koshtha',
          label: 'Koshtha',
          type: 'radio',
          options: [{ value: 'mridu', label: 'Mridu' }, { value: 'madhya', label: 'Madhya' }, { value: 'kroora', label: 'Kroora' }],
        },
        {
          key: 'bowel',
          label: 'Bowel Habits',
          type: 'radio',
          options: [{ value: 'regular', label: 'Regular' }, { value: 'irregular', label: 'Irregular' }, { value: 'constipated', label: 'Constipated' }],
        },
        {
          key: 'micturition',
          label: 'Micturition',
          type: 'select',
          options: [
            { value: 'normal', label: 'Normal' },
            { value: 'polyuria', label: 'Polyuria' },
            { value: 'scanty', label: 'Scanty' },
            { value: 'burning', label: 'Burning' },
          ],
        },
        { key: 'micturition_freq_day', label: 'Micturition Frequency — Day (times)', type: 'number' },
        { key: 'micturition_freq_night', label: 'Micturition Frequency — Night (times)', type: 'number' },
        {
          key: 'trishna',
          label: 'Trishna (Thirst)',
          type: 'radio',
          options: [{ value: 'heena', label: 'Heena' }, { value: 'madhya', label: 'Madhya' }, { value: 'adhika', label: 'Adhika' }],
        },
        {
          key: 'appetite',
          label: 'Appetite',
          type: 'select',
          options: [
            { value: 'normal', label: 'Normal' },
            { value: 'reduced', label: 'Reduced' },
            { value: 'compulsive', label: 'Compulsive Eater' },
            { value: 'increased', label: 'Increased' },
          ],
        },
        {
          key: 'emotional_status',
          label: 'Emotional Status',
          type: 'select',
          options: [
            { value: 'normal', label: 'Normal' },
            { value: 'jolly', label: 'Jolly' },
            { value: 'tensive', label: 'Tensive' },
            { value: 'anxiety', label: 'Anxiety' },
            { value: 'depression', label: 'Depression' },
          ],
        },
        {
          key: 'nidra',
          label: 'Nidra (Sleep Quality)',
          type: 'radio',
          options: [
            { value: 'samyaka', label: 'Samyaka' },
            { value: 'ati_nidra', label: 'Ati Nidra' },
            { value: 'alpa', label: 'Alpa' },
            { value: 'anidra', label: 'Anidra' },
          ],
        },
        { key: 'sleep_day', label: 'Sleep — Day (hrs)', type: 'number' },
        { key: 'sleep_night', label: 'Sleep — Night (hrs)', type: 'number' },
        {
          key: 'sharira',
          label: 'Sharira (Body Type)',
          type: 'radio',
          options: [{ value: 'sthoola', label: 'Sthoola' }, { value: 'krisha', label: 'Krisha' }, { value: 'madhyama', label: 'Madhyama' }],
        },
        {
          key: 'addiction',
          label: 'Addiction',
          type: 'select',
          options: [
            { value: 'tea', label: 'Tea' },
            { value: 'coffee', label: 'Coffee' },
            { value: 'tobacco', label: 'Tobacco' },
            { value: 'alcohol', label: 'Alcohol' },
            { value: 'smoking', label: 'Smoking' },
            { value: 'none', label: 'None' },
          ],
        },
        {
          key: 'exercise',
          label: 'Exercise Habits',
          type: 'radio',
          options: [{ value: 'alpa', label: 'Alpa' }, { value: 'samyaka', label: 'Samyaka' }, { value: 'ati', label: 'Ati' }],
        },
        { key: 'menstrual_obstetric', label: 'Menstrual & Obstetric History (Female)', type: 'textarea' },
      ],
    },

    // 4. GENERAL PHYSICAL EXAMINATION + VITAL SIGNS GRID
    {
      key: 'gpe',
      title: '4. General Physical Examination',
      fields: [
        {
          key: 'vitals_grid',
          label: 'Vital Signs — BT / Visit 1–6 / AT / Diff',
          type: 'assessment_grid',
          rows: [
            'Pulse Rate (/min)',
            'Blood Pressure (mmHg)',
            'Respiratory Rate (/min)',
            'Temperature (°F)',
            'Body Weight (kg)',
          ],
          columns: ['BT', 'Visit-1', 'Visit-2', 'Visit-3', 'Visit-4', 'Visit-5', 'Visit-6', 'AT', 'Diff'],
        },
        { key: 'look', label: 'Look', type: 'text' },
        {
          key: 'built',
          label: 'Built',
          type: 'radio',
          options: [{ value: 'average', label: 'Average' }, { value: 'emaciated', label: 'Emaciated' }, { value: 'well_built', label: 'Well Built' }],
        },
        {
          key: 'nutrition',
          label: 'Nutrition',
          type: 'radio',
          options: [{ value: 'mod', label: 'Moderately Nourished' }, { value: 'mal', label: 'Malnourished' }, { value: 'well', label: 'Well Nourished' }],
        },
        { key: 'height', label: 'Height (m)', type: 'number' },
        { key: 'skin', label: 'Skin', type: 'text' },
        { key: 'nail', label: 'Nails', type: 'text' },
        { key: 'head', label: 'Head', type: 'text' },
        { key: 'ear', label: 'Ears', type: 'text' },
        { key: 'eyes', label: 'Eyes', type: 'text' },
        { key: 'nose', label: 'Nose', type: 'text' },
        { key: 'mouth', label: 'Mouth', type: 'text' },
        { key: 'tongue', label: 'Tongue', type: 'text' },
        {
          key: 'pallor',
          label: 'Pallor',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'icterus',
          label: 'Icterus',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'cyanosis',
          label: 'Cyanosis',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'clubbing',
          label: 'Clubbing',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'oedema',
          label: 'Oedema',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
        {
          key: 'lymphadenopathy',
          label: 'Lymphadenopathy',
          type: 'radio',
          options: [{ value: '0', label: 'Absent' }, { value: '1', label: 'Present' }],
        },
      ],
    },

    // 5. ASHTAVIDHA PARIKSHA
    {
      key: 'ashtavidha',
      title: '5. Ashtavidha Pariksha',
      fields: [
        {
          key: 'nadi_dosha',
          label: 'Nadi — Dosha',
          type: 'select',
          options: [
            { value: 'V', label: 'Vata' }, { value: 'P', label: 'Pitta' }, { value: 'K', label: 'Kapha' },
            { value: 'VP', label: 'Vata-Pitta' }, { value: 'VK', label: 'Vata-Kapha' }, { value: 'PK', label: 'Pitta-Kapha' },
            { value: 'Tri', label: 'Tridoshaja' },
          ],
        },
        {
          key: 'nadi_rhythm',
          label: 'Nadi — Rhythm',
          type: 'radio',
          options: [{ value: 'regular', label: 'Regular' }, { value: 'irregular', label: 'Irregular' }],
        },
        { key: 'mutra_matra', label: 'Mutra — Matra (Volume)', type: 'text' },
        { key: 'mutra_varna', label: 'Mutra — Varna (Colour)', type: 'text' },
        { key: 'mutra_gandha', label: 'Mutra — Gandha (Smell)', type: 'text' },
        { key: 'mutra_pravritti', label: 'Mutra — Pravritti', type: 'text' },
        { key: 'mala_matra', label: 'Mala — Matra', type: 'text' },
        { key: 'mala_varna', label: 'Mala — Varna', type: 'text' },
        { key: 'mala_gandha', label: 'Mala — Gandha', type: 'text' },
        { key: 'mala_pravritti', label: 'Mala — Pravritti', type: 'text' },
        {
          key: 'mala_sama',
          label: 'Mala — Sama / Nirama',
          type: 'radio',
          options: [{ value: 'sama', label: 'Sama' }, { value: 'nirama', label: 'Nirama' }],
        },
        {
          key: 'jihwa',
          label: 'Jihwa (Tongue)',
          type: 'radio',
          options: [{ value: 'sama', label: 'Sama' }, { value: 'niram', label: 'Niram' }],
        },
        { key: 'jihwa_varna', label: 'Jihwa — Varna', type: 'text' },
        {
          key: 'shabda',
          label: 'Shabda (Voice)',
          type: 'select',
          options: [
            { value: 'spashta', label: 'Spashta' },
            { value: 'aspashta', label: 'Aspashta' },
            { value: 'gadgad', label: 'Gadgad' },
            { value: 'sanunasika', label: 'Sanunasika' },
          ],
        },
        {
          key: 'sparsha',
          label: 'Sparsha (Touch)',
          type: 'select',
          options: [
            { value: 'mridu', label: 'Mridu' }, { value: 'kathina', label: 'Kathina' },
            { value: 'sheeta', label: 'Sheeta' }, { value: 'ushna', label: 'Ushna' },
            { value: 'ruksha', label: 'Ruksha' }, { value: 'snigdha', label: 'Snigdha' },
            { value: 'khara', label: 'Khara' }, { value: 'slaksha', label: 'Slaksha' },
          ],
        },
        {
          key: 'drik',
          label: 'Drik (Eyes)',
          type: 'select',
          options: [
            { value: 'shwetabha', label: 'Shwetabha' }, { value: 'raktabha', label: 'Raktabha' },
            { value: 'peetabha', label: 'Peetabha' }, { value: 'anya', label: 'Anya' },
          ],
        },
        {
          key: 'akriti',
          label: 'Akriti (Body Frame)',
          type: 'select',
          options: [
            { value: 'krisha', label: 'Krisha' }, { value: 'sthool', label: 'Sthool' },
            { value: 'deergha', label: 'Deergha' }, { value: 'hriswa', label: 'Hriswa' },
            { value: 'samopachita', label: 'Samopachita' }, { value: 'vishamopachita', label: 'Vishamopachita' },
          ],
        },
      ],
    },

    // 6. DASHAVIDHA PARIKSHA
    {
      key: 'dashavidha',
      title: '6. Dashavidha Pariksha',
      fields: [
        {
          key: 'prakriti_sharirik',
          label: 'Prakriti — Sharirik',
          type: 'select',
          options: [
            { value: 'V', label: 'Vataja' }, { value: 'P', label: 'Pittaja' }, { value: 'K', label: 'Kaphaja' },
            { value: 'VP', label: 'Vata-Pittaja' }, { value: 'VK', label: 'Vata-Kaphaja' },
            { value: 'PK', label: 'Pitta-Kaphaja' }, { value: 'Tri', label: 'Samdoshaj' },
          ],
        },
        {
          key: 'prakriti_mansika',
          label: 'Prakriti — Mansika',
          type: 'radio',
          options: [{ value: 'satvic', label: 'Satvic' }, { value: 'rajas', label: 'Rajas' }, { value: 'tamas', label: 'Tamas' }],
        },
        { key: 'vikriti', label: 'Vikriti', type: 'text' },
        { key: 'hetu', label: 'Hetu (Causative Factor)', type: 'textarea' },
        { key: 'dosha', label: 'Dosha', type: 'text' },
        { key: 'dushya', label: 'Dushya', type: 'text' },
        { key: 'prakriti_desha', label: 'Desha', type: 'text' },
        { key: 'kala', label: 'Kala', type: 'text' },
        { key: 'bala', label: 'Bala', type: 'text' },
        {
          key: 'saara',
          label: 'Saara',
          type: 'select',
          options: [
            { value: 'twaka', label: 'Twaka Saara' }, { value: 'rakta', label: 'Rakta Saara' },
            { value: 'mansa', label: 'Mansa Saara' }, { value: 'meda', label: 'Meda Saara' },
            { value: 'asthi', label: 'Asthi Saara' }, { value: 'majja', label: 'Majja Saara' },
            { value: 'shukra', label: 'Shukra Saara' }, { value: 'satwa', label: 'Satwa Saara' },
            { value: 'sarva', label: 'Sarvasara' },
          ],
        },
        {
          key: 'samhanana',
          label: 'Samhanana',
          type: 'radio',
          options: [{ value: 'susanhata', label: 'Susanhata' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'heena', label: 'Heena' }],
        },
        {
          key: 'pramana',
          label: 'Pramana',
          type: 'radio',
          options: [{ value: 'sama', label: 'Sama' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'heena', label: 'Heena' }],
        },
        {
          key: 'satmya',
          label: 'Satmya',
          type: 'radio',
          options: [{ value: 'pravar', label: 'Pravar' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'avara', label: 'Avara' }],
        },
        {
          key: 'satwa',
          label: 'Satwa',
          type: 'radio',
          options: [{ value: 'pravar', label: 'Pravar' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'avara', label: 'Avara' }],
        },
        {
          key: 'ahara_shakti',
          label: 'Ahara Shakti (Abhyavaharana + Jarana)',
          type: 'radio',
          options: [{ value: 'pravar', label: 'Pravar' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'avara', label: 'Avara' }],
        },
        {
          key: 'vyayama_shakti',
          label: 'Vyayama Shakti',
          type: 'radio',
          options: [{ value: 'pravar', label: 'Pravar' }, { value: 'madhyama', label: 'Madhyama' }, { value: 'avara', label: 'Avara' }],
        },
        {
          key: 'vaya',
          label: 'Vaya (Age Group)',
          type: 'radio',
          options: [{ value: 'bala', label: 'Balavastha' }, { value: 'madhyama', label: 'Madhyamavastha' }, { value: 'vridha', label: 'Vridhavastha' }],
        },
      ],
    },

    // 7. SYSTEMIC EXAMINATION
    {
      key: 'systemic_exam',
      title: '7. Systemic Examination',
      fields: [
        { key: 'cvs_inspection', label: 'CVS — Inspection', type: 'text' },
        { key: 'cvs_palpation', label: 'CVS — Palpation', type: 'text' },
        { key: 'cvs_percussion', label: 'CVS — Percussion', type: 'text' },
        { key: 'cvs_auscultation', label: 'CVS — Auscultation', type: 'text' },
        { key: 'rs_inspection', label: 'Respiratory — Inspection', type: 'text' },
        { key: 'rs_palpation', label: 'Respiratory — Palpation', type: 'text' },
        { key: 'rs_percussion', label: 'Respiratory — Percussion', type: 'text' },
        { key: 'rs_auscultation', label: 'Respiratory — Auscultation', type: 'text' },
        { key: 'gi_inspection', label: 'Digestive — Inspection', type: 'text' },
        { key: 'gi_palpation', label: 'Digestive — Palpation', type: 'text' },
        { key: 'gi_percussion', label: 'Digestive — Percussion', type: 'text' },
        { key: 'gi_auscultation', label: 'Digestive — Auscultation', type: 'text' },
        { key: 'cns_higher', label: 'CNS — Higher Functions', type: 'text' },
        { key: 'cns_consciousness', label: 'CNS — Consciousness', type: 'text' },
        { key: 'cns_intelligence', label: 'CNS — Intelligence', type: 'text' },
        { key: 'cns_memory', label: 'CNS — Memory', type: 'text' },
        { key: 'cns_speech', label: 'CNS — Speech', type: 'text' },
        { key: 'cns_mental_status', label: 'CNS — Mental Status', type: 'text' },
        { key: 'cns_cranial', label: 'CNS — Cranial Nerve Examination', type: 'textarea' },
      ],
    },

    // 8. ROGA PARIKSHA
    {
      key: 'roga_pariksha',
      title: '8. Roga Pariksha',
      fields: [
        { key: 'nidana', label: 'Nidana (Causative Factors)', type: 'textarea' },
        { key: 'samprapti_dosha', label: 'Samprapti Ghatak — Dosha', type: 'text' },
        { key: 'samprapti_dushya', label: 'Samprapti Ghatak — Dushya', type: 'text' },
        { key: 'samprapti_adhisthan', label: 'Samprapti Ghatak — Adhisthan', type: 'text' },
        { key: 'samprapti_strotas', label: 'Samprapti Ghatak — Strotas', type: 'text' },
        { key: 'samprapti_strotodushti', label: 'Samprapti Ghatak — Strotodushti', type: 'text' },
        { key: 'upsaya', label: 'Upsaya (Relieving Factors)', type: 'textarea' },
        { key: 'anupsaya', label: 'Anupsaya (Aggravating Factors)', type: 'textarea' },
        {
          key: 'sadhyasadhyata',
          label: 'Sadhyasadhyata (Prognosis)',
          type: 'radio',
          options: [
            { value: 'sadhya', label: 'Sadhya (Curable)' },
            { value: 'krichasadhya', label: 'Krichasadhya (Difficult to Cure)' },
            { value: 'yapya', label: 'Yapya (Palliable)' },
            { value: 'asadhya', label: 'Asadhya (Incurable)' },
          ],
        },
      ],
    },

    // 9. AYURVEDIC SYMPTOM ASSESSMENT (22 symptoms × 3 timepoints)
    {
      key: 'ayurvedic_symptoms',
      title: '9. Ayurvedic Symptom Assessment (Present=1 / Absent=0)',
      fields: [
        {
          key: 'symptoms_grid',
          label: 'Symptoms — Day 1 (BT) / After 45 Days / After 90 Days (AT)',
          type: 'assessment_grid',
          rows: [
            '1. Daurbalya (Debility)',
            '2. Arochaka (Anorexia)',
            '3. Avipaka (Indigestion)',
            '4. Varcho Mutra Graha (Constipation & Retention of Urine)',
            '5. Tama Pravesha (Darkness in Front of Eye)',
            '6. Pipasa (Excessive Thirst)',
            '7. Angamarda (Body Ache)',
            '8. Chardi (Vomiting)',
            '9. Murcha (Loss of Consciousness)',
            '10. Anga Sada (Tiredness)',
            '11. Kasa (Cough)',
            '12. Swasa (Dyspnea)',
            '13. Mradu Jwara / Manda Jwara (Mild Fever)',
            '14. Anaha (Flatulence)',
            '15. Agni Naash / Manda Agni (Loss of Appetite)',
            '16. Karshya (Emaciation)',
            '17. Aasaya Varasya (Abnormal Taste in Mouth)',
            '18. Parva Bheda (Pain in Joints of Digits)',
            '19. Kostha Vata Shool (Abdominal Pain)',
            '20. Udar Aruna Varna Vivarna (Discoloration of Abdominal Wall)',
            '21. Nila Hareet Haaridra Raji (Stretch Marks — Bluish/Greenish/Yellowish)',
            '22. Aati Pandu (Anaemia)',
          ],
          columns: ['Day 1 (BT)', 'After 45 Days', 'After 90 Days (AT)'],
        },
      ],
    },

    // 10. INVESTIGATIONS
    {
      key: 'investigations',
      title: '10. Laboratory Investigations',
      fields: [
        { key: 'usg_heading', label: 'Ultrasonography (Whole Abdomen)', type: 'heading' },
        { key: 'usg_bt', label: 'USG — BT Findings', type: 'textarea' },
        { key: 'usg_at', label: 'USG — AT Findings', type: 'textarea' },
        { key: 'fibroscan_bt', label: 'Fibroscan — BT Interpretation', type: 'textarea' },
        { key: 'fibroscan_at', label: 'Fibroscan — AT Interpretation', type: 'textarea' },
        { key: 'hae_heading', label: 'Haematology', type: 'heading' },
        { key: 'hb_bt', label: 'Haemoglobin BT (g/dL)', type: 'number' },
        { key: 'hb_at', label: 'Haemoglobin AT (g/dL)', type: 'number' },
        { key: 'tlc_bt', label: 'TLC BT', type: 'number' },
        { key: 'tlc_at', label: 'TLC AT', type: 'number' },
        { key: 'dlc_n_bt', label: 'DLC N% BT', type: 'number' },
        { key: 'dlc_e_bt', label: 'DLC E% BT', type: 'number' },
        { key: 'dlc_b_bt', label: 'DLC B% BT', type: 'number' },
        { key: 'dlc_l_bt', label: 'DLC L% BT', type: 'number' },
        { key: 'dlc_m_bt', label: 'DLC M% BT', type: 'number' },
        { key: 'dlc_n_at', label: 'DLC N% AT', type: 'number' },
        { key: 'dlc_e_at', label: 'DLC E% AT', type: 'number' },
        { key: 'dlc_b_at', label: 'DLC B% AT', type: 'number' },
        { key: 'dlc_l_at', label: 'DLC L% AT', type: 'number' },
        { key: 'dlc_m_at', label: 'DLC M% AT', type: 'number' },
        { key: 'esr_bt', label: 'ESR BT (mm)', type: 'number' },
        { key: 'esr_at', label: 'ESR AT (mm)', type: 'number' },
        { key: 'bs_heading', label: 'Blood Sugar & Insulin', type: 'heading' },
        { key: 'fbs_bt', label: 'Blood Sugar Fasting BT (mg/dL)', type: 'number' },
        { key: 'fbs_at', label: 'Blood Sugar Fasting AT (mg/dL)', type: 'number' },
        { key: 'ppbs_bt', label: 'Blood Sugar PP BT (mg/dL)', type: 'number' },
        { key: 'ppbs_at', label: 'Blood Sugar PP AT (mg/dL)', type: 'number' },
        { key: 'insulin_bt', label: 'Fasting Serum Insulin BT (mIU/L)', type: 'number' },
        { key: 'insulin_at', label: 'Fasting Serum Insulin AT (mIU/L)', type: 'number' },
        { key: 'lft_heading', label: 'LFT (Liver Function Tests)', type: 'heading' },
        { key: 'sgot_bt', label: 'SGOT / AST BT (karmen units/dL)', type: 'number' },
        { key: 'sgot_at', label: 'SGOT / AST AT (karmen units/dL)', type: 'number' },
        { key: 'sgpt_bt', label: 'SGPT / ALT BT (karmen units/dL)', type: 'number' },
        { key: 'sgpt_at', label: 'SGPT / ALT AT (karmen units/dL)', type: 'number' },
        { key: 'ggt_bt', label: 'GGT BT (U/L)', type: 'number' },
        { key: 'ggt_at', label: 'GGT AT (U/L)', type: 'number' },
        { key: 'tp_bt', label: 'Total Protein BT (g/dL)', type: 'number' },
        { key: 'tp_at', label: 'Total Protein AT (g/dL)', type: 'number' },
        { key: 'albumin_bt', label: 'S. Albumin BT (g/dL)', type: 'number' },
        { key: 'albumin_at', label: 'S. Albumin AT (g/dL)', type: 'number' },
        { key: 'globulin_bt', label: 'S. Globulin BT (g/dL)', type: 'number' },
        { key: 'globulin_at', label: 'S. Globulin AT (g/dL)', type: 'number' },
        { key: 'ag_ratio_bt', label: 'A/G Ratio BT', type: 'number' },
        { key: 'ag_ratio_at', label: 'A/G Ratio AT', type: 'number' },
        { key: 'dbil_bt', label: 'Direct Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'dbil_at', label: 'Direct Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'ibil_bt', label: 'Indirect Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'ibil_at', label: 'Indirect Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'tbil_bt', label: 'Total Bilirubin BT (mg/dL)', type: 'number' },
        { key: 'tbil_at', label: 'Total Bilirubin AT (mg/dL)', type: 'number' },
        { key: 'alp_bt', label: 'S. Alkaline Phosphatase BT (U/L)', type: 'number' },
        { key: 'alp_at', label: 'S. Alkaline Phosphatase AT (U/L)', type: 'number' },
        { key: 'kft_heading', label: 'KFT (Kidney Function Tests)', type: 'heading' },
        { key: 'urea_bt', label: 'Serum Urea BT (mg/dL)', type: 'number' },
        { key: 'urea_at', label: 'Serum Urea AT (mg/dL)', type: 'number' },
        { key: 'creatinine_bt', label: 'Serum Creatinine BT (mg/dL)', type: 'number' },
        { key: 'creatinine_at', label: 'Serum Creatinine AT (mg/dL)', type: 'number' },
        { key: 'uric_acid_bt', label: 'Uric Acid BT (mg/dL)', type: 'number' },
        { key: 'uric_acid_at', label: 'Uric Acid AT (mg/dL)', type: 'number' },
        { key: 'lipid_heading', label: 'Serum Lipid Profile', type: 'heading' },
        { key: 'chol_bt', label: 'S. Cholesterol BT (mg/dL)', type: 'number' },
        { key: 'chol_at', label: 'S. Cholesterol AT (mg/dL)', type: 'number' },
        { key: 'hdl_bt', label: 'HDLc BT (mg/dL)', type: 'number' },
        { key: 'hdl_at', label: 'HDLc AT (mg/dL)', type: 'number' },
        { key: 'ldl_bt', label: 'LDLc BT (mg/dL)', type: 'number' },
        { key: 'ldl_at', label: 'LDLc AT (mg/dL)', type: 'number' },
        { key: 'vldl_bt', label: 'VLDL BT (mg/dL)', type: 'number' },
        { key: 'vldl_at', label: 'VLDL AT (mg/dL)', type: 'number' },
        { key: 'tg_bt', label: 'Serum Triglycerides BT (mg/dL)', type: 'number' },
        { key: 'tg_at', label: 'Serum Triglycerides AT (mg/dL)', type: 'number' },
        { key: 'chol_hdl_bt', label: 'Cholesterol/HDLc Ratio BT', type: 'number' },
        { key: 'chol_hdl_at', label: 'Cholesterol/HDLc Ratio AT', type: 'number' },
        { key: 'ldl_hdl_bt', label: 'LDL/HDL Ratio BT', type: 'number' },
        { key: 'ldl_hdl_at', label: 'LDL/HDL Ratio AT', type: 'number' },
        { key: 'bmi_bt', label: 'BMI BT (kg/m²)', type: 'number' },
        { key: 'bmi_at', label: 'BMI AT (kg/m²)', type: 'number' },
        { key: 'whr_bt', label: 'Waist-Hip Circumference Ratio BT', type: 'number' },
        { key: 'whr_at', label: 'Waist-Hip Circumference Ratio AT', type: 'number' },
        { key: 'urine_heading', label: 'Urine Examination', type: 'heading' },
        {
          key: 'urine_sugar_bt',
          label: 'Urine Sugar BT',
          type: 'select',
          options: [{ value: '0', label: 'Nil' }, { value: '1', label: '+' }, { value: '2', label: '++' }, { value: '3', label: '+++' }],
        },
        {
          key: 'urine_sugar_at',
          label: 'Urine Sugar AT',
          type: 'select',
          options: [{ value: '0', label: 'Nil' }, { value: '1', label: '+' }, { value: '2', label: '++' }, { value: '3', label: '+++' }],
        },
        {
          key: 'urine_protein_bt',
          label: 'Urine Protein BT',
          type: 'select',
          options: [{ value: '0', label: 'Nil' }, { value: '1', label: '+' }, { value: '2', label: '++' }, { value: '3', label: '+++' }],
        },
        {
          key: 'urine_protein_at',
          label: 'Urine Protein AT',
          type: 'select',
          options: [{ value: '0', label: 'Nil' }, { value: '1', label: '+' }, { value: '2', label: '++' }, { value: '3', label: '+++' }],
        },
        { key: 'urine_wbc_bt', label: 'Urine WBC BT (cells/hpf)', type: 'number' },
        { key: 'urine_wbc_at', label: 'Urine WBC AT (cells/hpf)', type: 'number' },
        { key: 'urine_rbc_bt', label: 'Urine RBC BT (cells/hpf)', type: 'number' },
        { key: 'urine_rbc_at', label: 'Urine RBC AT (cells/hpf)', type: 'number' },
      ],
    },

    // 11. CLDQ-NASH QUESTIONNAIRE (36 questions × 3 timepoints)
    {
      key: 'cldq_nash',
      title: '11. CLDQ-NASH Questionnaire (7-point Likert Scale)',
      fields: [
        {
          key: 'cldq_grid',
          label: 'Score: 7=All of the time → 1=None of the time',
          type: 'assessment_grid',
          rows: [
            'Q1. Feeling of abdominal bloating',
            'Q2. Tired or fatigued',
            'Q3. Experienced bodily pain',
            'Q4. Felt sleepy during the day',
            'Q5. Experienced abdominal pain',
            'Q6. Shortness of breath in daily activities',
            'Q7. Not been able to eat as much as you would like',
            'Q8. Bothered by decreased strength',
            'Q9. Trouble lifting or carrying heavy objects',
            'Q10. Felt anxious',
            'Q11. Felt a decreased level of energy',
            'Q12. Felt unhappy',
            'Q13. Felt drowsy',
            'Q14. Bothered by a limitation of your diet',
            'Q15. Been irritable',
            'Q16. Difficulty sleeping at night',
            'Q17. Feeling of abdominal discomfort',
            'Q18. Worried about impact of liver disease on family',
            'Q19. Had mood swings',
            'Q20. Unable to fall asleep at night',
            'Q21. Had muscle cramps',
            'Q22. Worried that symptoms will develop into major problems',
            'Q23. Had a dry mouth',
            'Q24. Felt depressed',
            'Q25. Worried about condition getting worse',
            'Q26. Had problems concentrating',
            'Q27. Troubled by itching',
            'Q28. Worried about never feeling any better',
            'Q29. Concerned about availability of a liver for transplant',
            'Q30. Trouble walking 2 blocks or climbing 2 flights of stairs',
            'Q31. Trouble bending, lifting, or stooping',
            'Q32. Felt you may die earlier because of fatty liver',
            'Q33. Felt distressed by having fatty liver',
            'Q34. Not enjoyed life',
            'Q35. Felt the need to take naps (5 min or longer) during the day',
            'Q36. Experiencing joint pain',
          ],
          columns: ['Day 1 (BT)', 'After 45 Days', 'After 90 Days (AT)'],
        },
        { key: 'cldq_total_bt', label: 'CLDQ-NASH Total Score — Day 1 (BT)', type: 'number' },
        { key: 'cldq_total_45', label: 'CLDQ-NASH Total Score — After 45 Days', type: 'number' },
        { key: 'cldq_total_at', label: 'CLDQ-NASH Total Score — After 90 Days (AT)', type: 'number' },
      ],
    },

    // 12. ADVERSE EVENTS & TREATMENT COMPLETION
    {
      key: 'adverse_completion',
      title: '12. Adverse Events & Treatment Completion',
      fields: [
        { key: 'pathya_apathya', label: 'Pathya-Apathya (Dietary Advice Given)', type: 'textarea' },
        {
          key: 'adverse_event',
          label: 'Any Adverse Drug Reaction / Adverse Event',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        { key: 'adverse_date', label: 'Adverse Event — Date', type: 'date' },
        { key: 'adverse_complaint', label: 'Adverse Event — Complaint', type: 'textarea' },
        { key: 'adverse_treatment', label: 'Adverse Event — Treatment Given', type: 'textarea' },
        { key: 'adverse_remarks', label: 'Adverse Event — Remarks', type: 'textarea' },
        {
          key: 'treatment_completed',
          label: 'Treatment Completed',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        {
          key: 'patient_dropout',
          label: 'Did the Patient Drop Out on Their Own?',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        { key: 'dropout_date', label: 'Dropout Date', type: 'date' },
        { key: 'dropout_reason', label: 'Dropout Reasons', type: 'textarea' },
        {
          key: 'patient_withdrawn',
          label: 'Was the Patient Withdrawn from the Trial?',
          type: 'radio',
          options: [{ value: '1', label: 'Yes' }, { value: '2', label: 'No' }],
        },
        { key: 'withdrawal_date', label: 'Withdrawal Date', type: 'date' },
        { key: 'withdrawal_reason', label: 'Withdrawal Reasons', type: 'textarea' },
        {
          key: 'final_result',
          label: 'Final Result',
          type: 'radio',
          options: [{ value: '1', label: 'Improved' }, { value: '0', label: 'Not Improved' }],
        },
      ],
    },
  ],
}
